name: Add slide
description: Add a new slide to Wrapped
title: "Add [replaceme] slide"
labels: ["slide"]
body:
  - type: input
    id: name
    attributes:
      label: Slide name
      description: What will this slide be called?
      placeholder: ex. SpendingByLocation
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: Slide information
      description: What's going to be on this slide?
      placeholder: Please try to be thorough and include info like the stats used, the content of the slide, and the design you have in mind
    validations:
      required: true
